#spring.application.name=ecom
#
#spring.h2.console.enabled = true
#spring.datasource.url = jdbc:h2:mem:test

spring:
  application:
    name: ecom-application
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: postgres
    password: ps1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true



