spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\web\Java\E-Commerce\Monolithic\config-mgmt\configserver\src\main\resources\config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:mysql://localhost:3306/configdb
#    username: root
#    password: Tarun@1234567890
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: "select prop_key, prop_value from configdb.properties where application = ? and profile = ? and label = ?"
#          default-label: main
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Tarun15111/app-configuration
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}

server:
  port: 8888

#encrypt:
#  key: "0E329232EA6D0D73"

encrypt:
  key-store:
    location: config-server.jks
    password: mypass
    alias: config-server-key
